version: '3.9'

services:
  dec-2022-postgres:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: dec-2022
    volumes:
      - dec-2022-db:/var/lib/postgresql/dec-2022

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - dec-2022-db:/var/lib/redis/dec-2022
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  dec-2022-db: