version: '3.9'

services:
  dec-2022-postgres:
    image: postgis/postgis
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: dec-2022
    volumes:
      - dec-2022-db:/var/lib/postgresql/dec-2022

volumes:
  dec-2022-db: